# Generated by Django 4.0.1 on 2022-01-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_rename_lectures_lecture'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
