# Generated by Django 4.0.1 on 2022-01-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lectures',
            new_name='Lecture',
        ),
    ]
