# Generated by Django 4.0.1 on 2022-01-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Periods',
            new_name='Period',
        ),
    ]
